const API='https://api.binance.com/api/v3/klines';
const KEY='binancePaperV1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{equity:2000,trades:[],positions:{},lastSignals:{},day:'',dailyTrades:0,lossStreak:0,maxEquity:2000,maxDrawdown:0};
const $=id=>document.getElementById(id);
let strategy={fast:5,slow:13,rsi:7,rsiBuy:55,sl:1,tp:2};
try{Object.assign(strategy,JSON.parse(localStorage.getItem('binanceStrategyV1')||'{}'))}catch{}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function fmt(n){return '₹'+Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function ema(values,p){let k=2/(p+1),e=values[0];for(let i=1;i<values.length;i++)e=values[i]*k+e*(1-k);return e}
function rsi(values,p){if(values.length<=p)return 50;let g=0,l=0;for(let i=values.length-p;i<values.length;i++){let d=values[i]-values[i-1];if(d>0)g+=d;else l-=d}return l===0?100:100-100/(1+g/l)}
function today(){return new Date().toISOString().slice(0,10)}
function resetDay(){if(state.day!==today()){state.day=today();state.dailyTrades=0;state.lossStreak=0;save()}}
async function fetchKlines(symbol){const u=`${API}?symbol=${symbol}&interval=5m&limit=60`;const r=await fetch(u);if(!r.ok)throw Error('Market data unavailable');return r.json()}
function signal(rows){const closes=rows.map(x=>+x[4]);const fast=ema(closes,strategy.fast),slow=ema(closes,strategy.slow),rv=rsi(closes,strategy.rsi);return {price:closes.at(-1),fast,slow,rsi:rv,buy:fast>slow&&rv>strategy.rsiBuy,reason:fast<=slow?'Fast EMA is not above slow EMA':rv<=strategy.rsiBuy?'RSI is below buy threshold':'All buy conditions passed'}}
function open(symbol,s){if(state.positions[symbol]||state.dailyTrades>=3||state.lossStreak>=3)return;const risk=state.equity*.01,entry=s.price,sl=entry*(1-strategy.sl/100),tp=entry*(1+strategy.tp/100);state.positions[symbol]={symbol,entry,sl,tp,risk,qty:risk/(entry*strategy.sl/100),openedAt:Date.now()};state.dailyTrades++;save()}
function close(symbol,price,reason){const p=state.positions[symbol];if(!p)return;const gross=(price-p.entry)*p.qty,fee=(p.entry*p.qty+price*p.qty)*0.001,slip=Math.abs(price)*p.qty*0.0002,net=gross-fee-slip;state.equity+=net;state.maxEquity=Math.max(state.maxEquity,state.equity);state.maxDrawdown=Math.max(state.maxDrawdown,state.maxEquity-state.equity);state.trades.push({symbol,side:'LONG',entry:p.entry,exit:price,reason,pnl:net,time:Date.now(),fees:fee,slippage:slip});if(net<0)state.lossStreak++;else state.lossStreak=0;delete state.positions[symbol];save()}
async function tick(){resetDay();const out=[];for(const symbol of ['BTCUSDT','ETHUSDT']){try{const rows=await fetchKlines(symbol),s=signal(rows);out.push({symbol,s});const p=state.positions[symbol];if(p){if(s.price<=p.sl)close(symbol,s.price,'Stop loss');else if(s.price>=p.tp)close(symbol,s.price,'Take profit');else if(!s.buy)close(symbol,s.price,'Signal exit')}else if(s.buy&&state.lossStreak<3&&state.dailyTrades<3)open(symbol,s)}catch(e){out.push({symbol,error:e.message})}}renderMarkets(out);render()}
function renderMarkets(data=[]){$('markets').innerHTML=data.map(x=>x.error?`<div class="market"><div><b>${x.symbol}</b><span>Feed error</span></div><div><b>—</b><span>${x.error}</span></div><div><b>—</b><span>Retrying</span></div></div>`:`<div class="market"><div><b>${x.symbol}</b><span>Price ${fmt(x.s.price)}</span></div><div><b>EMA ${strategy.fast}: ${x.s.fast.toFixed(2)}</b><span>EMA ${strategy.slow}: ${x.s.slow.toFixed(2)}</span></div><div><b>${x.s.buy?'BUY':'NO TRADE'}</b><span>RSI ${strategy.rsi}: ${x.s.rsi.toFixed(1)} · ${x.s.reason}</span></div></div>`).join('')||'<div class="notice">Loading market data…</div>'}
function render(){const wins=state.trades.filter(t=>t.pnl>0).length,grossWin=state.trades.filter(t=>t.pnl>0).reduce((a,t)=>a+t.pnl,0),grossLoss=Math.abs(state.trades.filter(t=>t.pnl<0).reduce((a,t)=>a+t.pnl,0));$('equity').textContent=fmt(state.equity);$('pnl').textContent=fmt(state.equity-2000);$('winRate').textContent=(state.trades.length?wins/state.trades.length*100:0).toFixed(1)+'%';$('tradeCount').textContent=`${state.trades.length} / 100`;$('journalMeta').textContent=state.trades.length?`${state.trades.length} completed · ${state.lossStreak} loss streak`:'No completed trades';$('riskMessage').textContent=state.lossStreak>=3?'Trading paused: 3 consecutive losses.':state.dailyTrades>=3?'Daily trade limit reached.':'Paper engine active. Live orders are disabled.';$('journal').innerHTML=state.trades.slice().reverse().map((t,i)=>`<tr><td>${state.trades.length-i}</td><td>${t.symbol}</td><td>${t.side}</td><td>${fmt(t.entry)}</td><td>${fmt(t.exit)}</td><td>${t.reason}</td><td class="${t.pnl>=0?'positive':'negative'}">${fmt(t.pnl)}</td></tr>`).join('')||'<tr><td colspan="7">No completed paper trades yet.</td></tr>';const pf=grossLoss?grossWin/grossLoss:0;$('metrics').innerHTML=`<div><span>Profit factor</span><b>${pf?pf.toFixed(2):'—'}</b></div><div><span>Max drawdown</span><b>${fmt(state.maxDrawdown||0)}</b></div><div><span>Open positions</span><b>${Object.keys(state.positions).length}</b></div>`}
$('saveStrategy').onclick=()=>{strategy={fast:+$('fastEma').value,slow:+$('slowEma').value,rsi:+$('rsiPeriod').value,rsiBuy:+$('rsiBuy').value,sl:+$('slPct').value,tp:+$('tpPct').value};localStorage.setItem('binanceStrategyV1',JSON.stringify(strategy));tick()};
$('resetBtn').onclick=()=>{if(confirm('Reset the virtual account and trade journal?')){localStorage.removeItem(KEY);location.reload()}};
render();tick();setInterval(tick,30000);
