const API='https://api.binance.com/api/v3/klines';
const KEY='binancePaperV1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{equity:2000,trades:[],positions:{},lastSignals:{},day:'',dailyTrades:0,lossStreak:0};
const $=id=>document.getElementById(id);
let strategy={fast:5,slow:13,rsi:7,rsiBuy:55,sl:1,tp:2};
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function fmt(n){return '₹'+Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function ema(values,p){let k=2/(p+1),e=values[0];for(let i=1;i<values.length;i++)e=values[i]*k+e*(1-k);return e}
function rsi(values,p){if(values.length<=p)return 50;let g=0,l=0;for(let i=values.length-p;i<values.length;i++){let d=values[i]-values[i-1];if(d>0)g+=d;else l-=d}return l===0?100:100-100/(1+g/l)}
function today(){return new Date().toISOString().slice(0,10)}
function resetDay(){if(state.day!==today()){state.day=today();state.dailyTrades=0;state.lossStreak=0;save()}}
async function fetchKlines(symbol){let u=`${API}?symbol=${symbol}&interval=5m&limit=60`;let r=await fetch(u);if(!r.ok)throw Error('Market data unavailable');return r.json()}
function signal(rows){let closes=rows.map(x=>+x[4]);let fast=ema(closes,strategy.fast),slow=ema(closes,strategy.slow),rv=rsi(closes,strategy.rsi);return {price:closes.at(-1),fast,slow,rsi:rv,buy:fast>slow&&rv>strategy.rsiBuy}}
function open(symbol,s){if(state.positions[symbol]||state.dailyTrades>=3||state.lossStreak>=3)return;let risk=state.equity*.01;let entry=s.price;let sl=entry*(1-strategy.sl/100),tp=entry*(1+strategy.tp/100);state.positions[symbol]={symbol,entry,sl,tp,risk,qty:risk/(entry*strategy.sl/100),openedAt:Date.now()};state.dailyTrades++;save()}
function close(symbol,price,reason){let p=state.positions[symbol];if(!p)return;let gross=(price-p.entry)*p.qty;let fee=(p.entry*p.qty+price*p.qty)*0.001;let slip=Math.abs(price)*p.qty*0.0002;let net=gross-fee-slip;state.equity+=net;state.trades.push({symbol,side:'LONG',entry:p.entry,exit:price,reason,pnl:net,time:Date.now()});if(net<0)state.lossStreak++;else state.lossStreak=0;delete state.positions[symbol];save()}
async function tick(){resetDay();let out=[];for(const symbol of ['BTCUSDT','ETHUSDT']){try{let rows=await fetchKlines(symbol),s=signal(rows);out.push({symbol,s});let p=state.positions[symbol];if(p){if(s.price<=p.sl)close(symbol,s.price,'Stop loss');else if(s.price>=p.tp)close(symbol,s.price,'Take profit');else if(!s.buy)close(symbol,s.price,'Signal exit')}else if(s.buy&&state.lossStreak<3&&state.dailyTrades<3)open(symbol,s)}catch(e){out.push({symbol,error:e.message})}}renderMarkets(out);render()}
function renderMarkets(data=[]){$('markets').innerHTML=data.map(x=>x.error?`<div class="market"><b>${x.symbol}</b><span>Feed error</span><span>${x.error}</span></div>`:`<div class="market"><div><b>${x.symbol}</b><span>Price</span></div><div><b>${fmt(x.s.price)}</b><span>EMA ${strategy.fast}: ${x.s.fast.toFixed(2)}</span></div><div><b>${x.s.buy?'BUY':'NO TRADE'}</b><span>RSI: ${x.s.rsi.toFixed(1)}</span></div></div>`).join('')||'<div class="notice">Loading market data…</div>'}
function render(){let wins=state.trades.filter(t=>t.pnl>0).length;let losses=state.trades.filter(t=>t.pnl<0);let grossWin=state.trades.filter(t=>t.pnl>0).reduce((a,t)=>a+t.pnl,0),grossLoss=Math.abs(losses.reduce((a,t)=>a+t.pnl,0));$('equity').textContent=fmt(state.equity);$('pnl').textContent=fmt(state.equity-2000);$('winRate').textContent=(state.trades.length?(wins/state.trades.length*100):0).toFixed(1)+'%';$('tradeCount').textContent=`${state.trades.length} / 100`;$('journalMeta').textContent=state.trades.length?`${state.trades.length} completed · ${state.lossStreak} loss streak`:'No completed trades';$('riskMessage').textContent=state.lossStreak>=3?'Trading paused: 3 consecutive losses.':state.dailyTrades>=3?'Daily trade limit reached.':'Paper engine active. Live orders are disabled.';$('journal').innerHTML=state.trades.slice().reverse().map((t,i)=>`<tr><td>${state.trades.length-i}</td><td>${t.symbol}</td><td>${t.side}</td><td>${fmt(t.entry)}</td><td>${fmt(t.exit)}</td><td>${t.reason}</td><td class="${t.pnl>=0?'positive':'negative'}">${fmt(t.pnl)}</td></tr>`).join('')||'<tr><td colspan="7">No completed paper trades yet.</td></tr>';window.profitFactor=grossLoss?grossWin/grossLoss:null}
$('saveStrategy').onclick=()=>{strategy={fast:+$('fastEma').value,slow:+$('slowEma').value,rsi:+$('rsiPeriod').value,rsiBuy:+$('rsiBuy').value,sl:+$('slPct').value,tp:+$('tpPct').value};localStorage.setItem('binanceStrategyV1',JSON.stringify(strategy));tick()};
$('resetBtn').onclick=()=>{if(confirm('Reset the virtual account and trade journal?')){localStorage.removeItem(KEY);location.reload()}};
try{Object.assign(strategy,JSON.parse(localStorage.getItem('binanceStrategyV1')||'{}'))}catch{}
$('feedStatus').textContent='Public Binance market feed · Paper only';render();tick();setInterval(tick,30000);
