import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const API='https://api.india.delta.exchange/v2/tickers?contract_types=perpetual_futures';
const CANDLE_API='https://api.india.delta.exchange/v2/history/candles';
const REFRESH_MS=15000;
const ANALYSE_LIMIT=30;
const START_CAPITAL=10000;
const SL_PCT=1;
const TP_PCT=2;
const SIGNAL_COOLDOWN_MS=5*60*1000;
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function money(v){v=Math.abs(num(v));if(v>=1e9)return '$'+(v/1e9).toFixed(2)+'B';if(v>=1e6)return '$'+(v/1e6).toFixed(2)+'M';if(v>=1e3)return '$'+(v/1e3).toFixed(1)+'K';return '$'+v.toFixed(0)}
function price(v){return num(v).toLocaleString('en-US',{maximumFractionDigits:8})}
function percentile(a,v){return a.length?a.filter(x=>x<=v).length/a.length*100:0}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
async function candles(symbol,resolution,count){const end=Math.floor(Date.now()/1000),sec=resolution==='5m'?300:900,start=end-sec*(count+3);const r=await fetch(`${CANDLE_API}?resolution=${resolution}&symbol=${encodeURIComponent(symbol)}&start=${start}&end=${end}`,{cache:'no-store'});if(!r.ok)throw Error('Candle HTTP '+r.status);const j=await r.json();return Array.isArray(j.result)?j.result.sort((a,b)=>num(a.time)-num(b.time)):[]}
function trend(d){const c=d.map(x=>num(x.close)).filter(x=>x>0);if(c.length<3)return'WAIT';const last=c.at(-1),prev=c.at(-2),p=Math.min(5,c.length),k=2/(p+1);let e=c[0];for(let i=1;i<c.length;i++)e=c[i]*k+e*(1-k);return last>prev&&last>e?'BULLISH':last<prev&&last<e?'BEARISH':'WAIT'}
function spike(d){const v=d.map(x=>num(x.volume));if(v.length<5)return 0;const base=avg(v.slice(Math.max(0,v.length-21),-1));return base>0?v.at(-1)/base:0}
async function enrich(s){try{const[a,b]=await Promise.all([candles(s,'5m',25),candles(s,'15m',12)]);return{trend5:trend(a),trend15:trend(b),volumeSpike:spike(a)}}catch{return{trend5:'WAIT',trend15:'WAIT',volumeSpike:0}}}
async function sendTelegram(message){try{const r=await fetch('/api/telegram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});return r.ok}catch{return false}}
function App(){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(null),[minChange,setMinChange]=useState(1),[minVolume,setMinVolume]=useState(100000),[side,setSide]=useState('ALL'),[sort,setSort]=useState('score'),[search,setSearch]=useState(''),[analysis,setAnalysis]=useState(false);
 const[paper,setPaper]=useState(()=>localStorage.getItem('delta-paper-on')==='1'),[capital,setCapital]=useState(()=>Number(localStorage.getItem('delta-paper-capital')||START_CAPITAL)),[riskPct,setRiskPct]=useState(()=>Number(localStorage.getItem('delta-paper-risk')||10)),[positions,setPositions]=useState(()=>JSON.parse(localStorage.getItem('delta-paper-positions')||'[]')),[trades,setTrades]=useState(()=>JSON.parse(localStorage.getItem('delta-paper-trades')||'[]')),[telegram,setTelegram]=useState(()=>localStorage.getItem('delta-telegram-on')==='1');
 const signalSeen=useRef(new Map());
 useEffect(()=>localStorage.setItem('delta-paper-on',paper?'1':'0'),[paper]);useEffect(()=>localStorage.setItem('delta-paper-capital',capital),[capital]);useEffect(()=>localStorage.setItem('delta-paper-risk',riskPct),[riskPct]);useEffect(()=>localStorage.setItem('delta-paper-positions',JSON.stringify(positions)),[positions]);useEffect(()=>localStorage.setItem('delta-paper-trades',JSON.stringify(trades)),[trades]);useEffect(()=>localStorage.setItem('delta-telegram-on',telegram?'1':'0'),[telegram]);
 const load=useCallback(async()=>{try{setAnalysis(true);const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw Error('Delta API HTTP '+r.status);const j=await r.json(),raw=Array.isArray(j.result)?j.result:[],perp=raw.filter(x=>x.symbol&&x.contract_type==='perpetual_futures'),vols=perp.map(x=>num(x.turnover_usd)).filter(x=>x>0),base=perp.map(x=>({...x,change:num(x.ltp_change_24h),vol:num(x.turnover_usd)})).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,ANALYSE_LIMIT),ds=await Promise.all(base.map(x=>enrich(x.symbol))),dm=new Map(base.map((x,i)=>[x.symbol,ds[i]]));const mapped=perp.map(x=>{const change=num(x.ltp_change_24h),vol=num(x.turnover_usd),d=dm.get(x.symbol)||{trend5:'WAIT',trend15:'WAIT',volumeSpike:0},score=Math.round(Math.min(Math.abs(change)/10,1)*40+percentile(vols,vol)/100*20+Math.min(Math.max(d.volumeSpike-1,0)/3,1)*20+(d.trend5===d.trend15&&d.trend5!=='WAIT'?20:0)),buy=change>=minChange&&score>=70&&d.trend5==='BULLISH'&&d.trend15==='BULLISH',sell=change<=-minChange&&score>=70&&d.trend5==='BEARISH'&&d.trend15==='BEARISH';return{...x,change,vol,...d,score,signal:buy?'BUY':sell?'SELL':'WATCH'}});setRows(mapped);setUpdated(new Date());setError('')}catch(e){setError(e.message||'Unable to load Delta market data')}finally{setLoading(false);setAnalysis(false)}},[minChange]);
 useEffect(()=>{load();const id=setInterval(load,REFRESH_MS);return()=>clearInterval(id)},[load]);
 const filtered=useMemo(()=>{let o=rows.filter(r=>r.vol>=minVolume&&Math.abs(r.change)>=minChange);if(side!=='ALL')o=o.filter(r=>r.signal===side);if(search)o=o.filter(r=>r.symbol.toLowerCase().includes(search.toLowerCase()));return[...o].sort((a,b)=>sort==='change'?Math.abs(b.change)-Math.abs(a.change):sort==='volume'?b.vol-a.vol:b.score-a.score)},[rows,minChange,minVolume,side,search,sort]);
 const stats=useMemo(()=>({total:rows.length,buy:rows.filter(r=>r.signal==='BUY').length,sell:rows.filter(r=>r.signal==='SELL').length,active:rows.filter(r=>Math.abs(r.change)>=minChange&&r.vol>=minVolume).length}),[rows,minChange,minVolume]);
 const paperStats=useMemo(()=>{const unreal=positions.reduce((s,p)=>{const r=rows.find(x=>x.symbol===p.symbol),px=r?num(r.close??r.mark_price):p.entry;return s+(p.side==='LONG'?(px-p.entry):(p.entry-px))*p.qty},0),real=trades.reduce((s,t)=>s+num(t.pnl),0),wins=trades.filter(t=>num(t.pnl)>0).length;return{unreal,real,equity:capital+unreal,wins,winRate:trades.length?wins/trades.length*100:0}},[positions,rows,trades,capital]);
 useEffect(()=>{if(!paper)return;setPositions(ps=>{const next=[];const closed=[];ps.forEach(p=>{const r=rows.find(x=>x.symbol===p.symbol);if(!r){next.push(p);return}const px=num(r.close??r.mark_price),pnl=(p.side==='LONG'?(px-p.entry):(p.entry-px))*p.qty,hit=(p.side==='LONG'&&px<=p.sl)||(p.side==='LONG'&&px>=p.tp)||(p.side==='SHORT'&&px>=p.sl)||(p.side==='SHORT'&&px<=p.tp);if(hit){closed.push({...p,exit:px,pnl,closedAt:new Date().toISOString()})}else next.push({...p,current:px,pnl})});if(closed.length){setTrades(ts=>[...closed,...ts].slice(0,100));setCapital(c=>c+closed.reduce((s,t)=>s+t.pnl,0))}return next})},[rows,paper]);
 useEffect(()=>{if(!paper)return;rows.filter(r=>r.signal==='BUY'||r.signal==='SELL').forEach(r=>{const now=Date.now(),key=`${r.symbol}:${r.signal}`,last=signalSeen.current.get(key)||0;if(now-last<SIGNAL_COOLDOWN_MS)return;setPositions(ps=>{if(ps.some(p=>p.symbol===r.symbol))return ps;const entry=num(r.close??r.mark_price);if(!entry)return ps;const allocation=Math.max(0,capital)*Math.min(Math.max(riskPct,1),100)/100,qty=allocation/entry,sl=r.signal==='BUY'?entry*(1-SL_PCT/100):entry*(1+SL_PCT/100),tp=r.signal==='BUY'?entry*(1+TP_PCT/100):entry*(1-TP_PCT/100);signalSeen.current.set(key,now);const pos={symbol:r.symbol,side:r.signal==='BUY'?'LONG':'SHORT',entry,qty,sl,tp,openedAt:new Date().toISOString(),signalScore:r.score};if(telegram)sendTelegram(`⚡ Delta Scanner\n${r.signal==='BUY'?'🟢 LONG':'🔴 SHORT'} PAPER SIGNAL\nSymbol: ${r.symbol}\nEntry: ${price(entry)}\nSL: ${price(sl)}\nTP: ${price(tp)}\nScore: ${r.score}\n24H: ${r.change.toFixed(2)}%\n5m: ${r.trend5} · 15m: ${r.trend15}\nVolume spike: ${r.volumeSpike?r.volumeSpike.toFixed(1)+'x':'—'}`);return[...ps,pos]})})},[rows,paper,capital,riskPct,telegram]);
 const reset=()=>{setPositions([]);setTrades([]);setCapital(START_CAPITAL);signalSeen.current.clear()};
 return <div className="app"><header><div><div className="brand">⚡ DELTA SCANNER</div><div className="sub">Delta Exchange India · Live Momentum + Volume Scanner</div></div><div className="live"><span/> LIVE · 15s</div></header>
 <section className="hero"><div><h1>Live Scanner</h1><p>24H momentum + volume spike + 5m/15m confirmation. Paper trading is simulated; real orders remain OFF.</p></div><button onClick={load} disabled={analysis}>{analysis?'Analysing…':'↻ Refresh'}</button></section>
 <div className="cards"><div className="card"><small>🧪 PAPER TRADING</small><strong className={paper?'up':'down'}>{paper?'ON':'OFF'}</strong><button className="toggle" onClick={()=>setPaper(!paper)}>{paper?'Turn OFF':'Turn ON'}</button></div><div className="card"><small>VIRTUAL EQUITY</small><strong>₹{paperStats.equity.toFixed(2)}</strong><span>Realised P&L ₹{paperStats.real.toFixed(2)} · Unrealised ₹{paperStats.unreal.toFixed(2)}</span></div><div className="card"><small>TRADING STATS</small><strong>{paperStats.winRate.toFixed(1)}%</strong><span>Win rate · {trades.length} total · {paperStats.wins} wins</span></div><div className="card"><small>STRONG SIGNALS</small><strong>{stats.buy+stats.sell}</strong><span>🟢 BUY {stats.buy} · 🔴 SELL {stats.sell}</span></div></div>
 <section className="paper panel"><div className="panelhead"><h2>🧪 Paper Trading Account</h2><span>Simulation only · no Delta order API</span></div><div className="papergrid"><label>Virtual Capital ₹<input type="number" value={capital} onChange={e=>setCapital(Number(e.target.value)||0)} disabled={positions.length>0}/></label><label>Allocation % <input type="number" min="1" max="100" value={riskPct} onChange={e=>setRiskPct(Number(e.target.value)||1)}/></label><button onClick={reset}>Reset Paper Account</button></div><div className="papernote">{paper?'🟢 ON: BUY → LONG, SELL → SHORT · SL 1% · TP 2% · duplicate protection 5 min':'⚪ OFF: signals remain informational only.'}</div></section>
 <section className="paper panel"><div className="panelhead"><h2>🔔 Telegram Alerts</h2><span>Optional Vercel environment variables</span></div><div className="papergrid"><button className="toggle" onClick={()=>setTelegram(!telegram)}>{telegram?'Telegram ON':'Telegram OFF'}</button><span className="papernote">Set <b>TELEGRAM_BOT_TOKEN</b> and <b>TELEGRAM_CHAT_ID</b> in Vercel before enabling alerts.</span></div></section>
 <section className="controls"><input placeholder="Search symbol…" value={search} onChange={e=>setSearch(e.target.value)}/><label>Min 24H % <input type="number" step="0.1" value={minChange} onChange={e=>setMinChange(Number(e.target.value)||0)}/></label><label>Min volume $ <input type="number" step="10000" value={minVolume} onChange={e=>setMinVolume(Number(e.target.value)||0)}/></label><select value={side} onChange={e=>setSide(e.target.value)}><option>ALL</option><option>BUY</option><option>SELL</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Score</option><option value="change">24H Change</option><option value="volume">Volume</option></select></section>
 {error&&<div className="error">⚠ {error}</div>}
 <section className="panel"><div className="panelhead"><h2>Market Scanner</h2><span>{stats.total} perpetuals · {updated?updated.toLocaleTimeString():'—'}</span></div><div className="tablewrap"><table><thead><tr><th>RANK</th><th>SYMBOL</th><th>LTP</th><th>24H CHANGE</th><th>VOLUME</th><th>SPIKE</th><th>5m</th><th>15m</th><th>STRENGTH</th><th>SIGNAL</th></tr></thead><tbody>{loading&&!rows.length?<tr><td colSpan="10" className="empty">Connecting…</td></tr>:filtered.slice(0,100).map((r,i)=><tr key={r.symbol}><td>#{i+1}</td><td className="symbol">{r.symbol}</td><td>{price(r.close??r.mark_price)}</td><td className={r.change>=0?'up':'down'}>{r.change>=0?'+':''}{r.change.toFixed(2)}%</td><td>{money(r.vol)}</td><td>{r.volumeSpike?r.volumeSpike.toFixed(1)+'x':'—'}</td><td className={r.trend5==='BULLISH'?'up':r.trend5==='BEARISH'?'down':''}>{r.trend5}</td><td className={r.trend15==='BULLISH'?'up':r.trend15==='BEARISH'?'down':''}>{r.trend15}</td><td><div className="score"><i style={{width:`${r.score}%`}}/><span>{r.score}</span></div></td><td><span className={`pill ${r.signal.toLowerCase()}`}>{r.signal}</span></td></tr>)}</tbody></table></div></section>
 <section className="panel history"><div className="panelhead"><h2>Paper Positions & Trade History</h2><span>{positions.length} open · {trades.length} closed</span></div>{positions.length?<div className="positions">{positions.map(p=>{const r=rows.find(x=>x.symbol===p.symbol),px=r?num(r.close??r.mark_price):p.entry,pnl=(p.side==='LONG'?(px-p.entry):(p.entry-px))*p.qty;return <div className="position" key={p.symbol}><b>{p.symbol}</b><span className={p.side==='LONG'?'up':'down'}>{p.side}</span><span>Entry {price(p.entry)} · Current {price(px)}</span><span className={pnl>=0?'up':'down'}>P&L ₹{pnl.toFixed(2)}</span><span>SL {price(p.sl)} · TP {price(p.tp)}</span></div>})}</div>:<div className="empty">No open paper positions. Turn Paper Trading ON and wait for a BUY/SELL signal.</div>}{trades.length>0&&<div className="trades"><h3>Closed Trades</h3>{trades.slice(0,20).map((t,i)=><div key={i}><b>{t.symbol}</b> {t.side} · Entry {price(t.entry)} → Exit {price(t.exit)} · <span className={t.pnl>=0?'up':'down'}>₹{t.pnl.toFixed(2)}</span></div>)}</div>}</section>
 <footer>Source: Delta Exchange India public market API · 5m/15m candles · Paper trading only · Real Delta order API is OFF.</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);